### ISSUE TITLE
function names have g!1!!

### ISSUE THREAD

**Issue by vooxal** [h-projects/h-projects.github.io#13]
in https://github.com/h-projects/h-projects.github.io/blob/master/app/fuck-g/fuck-g.js you have a `get` function!11! **g**et has a g!! i can't belive thisi haveb ben so betraied. also whyn ot use react!11!

**Comment by DevSadie** [comment]
Thanks For Suggesting This. Unfortunately, your suggestion is out of the scope of this project.

Sadie Katherine B.

**Comment by vooxal** [comment]
At least change it to an arrow function, its much more concise and nice looking

**Comment by DevSadie** [comment]
No, we won't.
