### ISSUE TITLE
Aytchsoftware.tk got unregistered somehow.

### ISSUE THREAD

**Issue by Senko-Dev** [h-projects/h-projects.github.io#7]
![image](https://user-images.githubusercontent.com/32780515/98918604-e055ef80-24de-11eb-83bb-7a4b49dafa78.png)
![image](https://user-images.githubusercontent.com/32780515/98918635-ea77ee00-24de-11eb-97a2-66da423ebb89.png)

just kill the cname

**Comment by Indexerrowaty** [comment]
🤔

**Comment by Indexerrowaty** [comment]
We are not using cname records.

**Comment by Indexerrowaty** [comment]
Or wait. We do.

**Comment by Indexerrowaty** [comment]
It's not possible to use other record type than CNAME with GitHub Pages.

**Comment by Indexerrowaty** [comment]
W8 wtf. How did the domain unregister!?
I'm working on getting it back.

**Comment by Indexerrowaty** [comment]
Can't get it back. ReCaptcha v3 and Freenom is retarded.

**Comment by Senko-Dev** [comment]
you are not neurodivergent
